### ISSUE TITLE
Usage with Handle -> IO ()?

### ISSUE THREAD

**Issue by Ancipital** [vincenthz/hs-connection#16]
Hello,

This appears to be a very useful package. But, I'm new to Haskell (like many people, LOL) and don't understand enough yet, so hope you can provide a bit of help. I'm trying to create an SSL connection with an IRC server - such a useful protocol for learning purposes.

With plain text connections, most examples show something roughly similar to the following (example taken from https://wiki.haskell.org/Roll_your_own_IRC_bot):

```haskell
import Network
import System.IO
 
server = "irc.freenode.org"
port   = 6667
 
main = do
    h <- connectTo server (PortNumber (fromIntegral port))
    hSetBuffering h NoBuffering
    t <- hGetContents h
    print t

```

But with Connections, I don't understand, because I can't work with handles, can I? Anyway, hope you can help newbies like myself understand a bit more. Thanks.

**Comment by vincenthz** [comment]
Did you have a look at the examples https://github.com/vincenthz/hs-connection/tree/master/examples ?
It should give you enough insight you to get started. a `Connection` object is very similar to a `Handle`, but you have to use the function coming from the `Network.Connection` module to write and read.

**Comment by Ancipital** [comment]
Yes, I did look at the examples, and am able to establish an SSL connection in the following way:

```haskell
main = do
    ctx <- initConnectionContext
    con <- connectTo ctx $ ConnectionParams
                              { connectionHostname  = myserver
                              , connectionPort      = myport
                              , connectionUseSecure = Just def
                              , connectionUseSocks  = Nothing
                              }
    connectionPut con . C.pack $ "NICK " ++ mynick
    r <- connectionGetChunk con
    putStrLn $ show r
    connectionClose con
```

This works nicely. But, referring to my previous example, should I do anything like `hSetBuffering h NoBuffering`?

And.. being greedy with my questions, hope you don't mind... :bowtie:

> you have to use the function coming from the Network.Connection module to write and read

For sending I guess this means using `ConnectionPut`. For receiving, I'm not sure.. would you recommend `ConnectionGetChunk`, or `ConnectionGetLine`... 

Thanks :+1:

**Comment by vincenthz** [comment]
`connectionGetLine` is practical for textual protocol like imap/pop3 or irc. Otherwise `connectionGet` is useful for a binary protocol.

`connectionGetChunk` is useful when you use a stream construction like `conduit`, `pipe` or `io-streams`

**Comment by Ancipital** [comment]
Thanks, @vincenthz. I have gotten it to work, thanks for helping.

This package does make SSL connections very simple. Nice work. :+1:
