### ISSUE TITLE
IPv6?

### ISSUE THREAD

**Issue by tolysz** [vincenthz/hs-connection#18]
Is there a way to specify that I do not want to use IPv6?

**Comment by fosskers** [comment]
This is currently breaking my software for many of my users in North America. Please help.

**Comment by vincenthz** [comment]
The part that actually create the client socket is in the `network` package `Network.connectTo` which doesn't have a way to specify the underlaying protocol. Which OS are you / your client using ? IIRC some system automatically choose to bind on AF_INET6 when you choose AF_INET unless you explicitly deactivate during your socket creation.

It would be ultimately a really good idea to provide first class support for this in `connection`.

**Comment by kudlatyamroth** [comment]
+1 we need that

**Comment by fosskers** [comment]
We're on Arch Linux, using `servant-client` and `http-client-tls` for HTTPS support.

**Comment by vincenthz** [comment]
Can you strace / ltrace the socket calls and couple of line before / after ?

**Comment by fosskers** [comment]
Maybe. As far as I can tell, the actually connection calls are all made by `http-client-tls` under the hood.

**Comment by vincenthz** [comment]
yes they are all made by http-client-tls with `NC.connectTo`.

The reason why I would like to see the strace is to see the result values for the resolution, which kind of socket types are created with which parameters, etc.

**Comment by fosskers** [comment]
Ok, I'll do some testing later on.
