### ISSUE TITLE
Some TLS connections fail

### ISSUE THREAD

**Issue by snoyberg** [vincenthz/hs-connection#6]
Consider the following example:

```haskell
import Network.Connection
import Data.Default

main :: IO ()
main = do
    context <- initConnectionContext
    conn <- connectTo context $ ConnectionParams "httpbin.org" 443 (Just def) Nothing
    return ()
```

This example errors out with the following message:

```
test.hs: HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")
```

I get the same error message when trying to connection to https://www.fpcomplete.com/ (which is using Amazon ELB's SSL capabilities), but the connection works to https://www.google.com/. However, all of these connections work correctly when using http-conduit.

**Comment by vincenthz** [comment]
I think this one has been solved already. reopen if not.

**Comment by delanoe** [comment]
Hello,
I get this error:
(InternalException (Terminated True "received fatal error: BadRecordMac" (Error_Protocol ("remote side fatal error",True,BadRecordMac))))

With installed:
- http-client-0.5.1
- http-client-tls-0.3.0
- http-conduit-2.2.0
- connection-0.2.6

I can give more informations if needed.
I have to downgrade some libs ?

Thanks.

**Comment by snoyberg** [comment]
Can you try upgrading to http-client-0.5.3.1?

On Tue, Sep 6, 2016 at 11:07 AM, Alexandre Delanoë <notifications@github.com

**Comment by delanoe** [comment]
Yes, http-client upgrade to 0.5.3.1
and I get again some:
(InternalException (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")))

**Comment by delanoe** [comment]
Any insight(s) ? Can you reproduce the bug ?

**Comment by delanoe** [comment]
Which version is still working for you please ?

**Comment by ocheron** [comment]
Connection to `httpbin.org` works fine with the following packages:
- connection-0.2.6
- cryptonite-0.20
- http-client-0.5.3.2
- http-client-tls-0.3.3
- http-conduit-2.2.2.1
- tls-1.3.8
- x509-1.6.4
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5

If you try to connect to another server which is not publicly accessible then you can find debugging information here: https://github.com/vincenthz/hs-tls#common-issues

**Comment by vincenthz** [comment]
@delanoe: are you connecting to httpbin.org ?

**Comment by delanoe** [comment]
Le 03 oct. 16, vers 22:54, Vincent Hanquez ecrivait:
> @delanoe: are you connecting to httpbin.org ?

I try to connect to a private server.

Thanks for the versions, I will test it and come back for the results.

Cheers,
-- 
Alexandre Delanoë

**Comment by vincenthz** [comment]
every https connection is different, it's better to open a new issue than piggy back on an old one. The error might be similar, but I don't think you have the same issue than above
