### ISSUE TITLE
Add connectionGet' that works like B.hGet

### ISSUE THREAD

**Issue by AlainODea** [vincenthz/hs-connection#9]
Here is an implementation I am using as part of in my changes to support TLS in the amqp package:

```haskell
connectionGet' :: Conn.Connection -> Int -> IO BC.ByteString
connectionGet' conn x = do
  bs <- Conn.connectionGet conn x
  let diff = BS.length bs - x
  if BS.length bs == 0 || diff == 0
    then do
      return bs
    else do
      next <- connectionGet' conn diff
      return $ BC.append bs next
```

Relevant qualified imports:

```haskell
import qualified Network.Connection as Conn
import qualified Data.ByteString as BS
import qualified Data.ByteString.Char8 as BC
```

**Comment by dagit** [comment]
I just ran into a problem using `connectionGet` and found this issue. The proposed solution works perfectly for me. Are you still planning to add `connectionGetExact` to the library? As a temporary solution I added `connectionGetExact` to my project, but it seems like a nice function to have in the official API.

**Comment by vincenthz** [comment]
sorry about the crappy delay. This shoudn't have take that long, I just didn't see it.

**Comment by AlainODea** [comment]
@vincenthz this and the family of crypto libraries around it are essential. Creting and maintaining them is a huge service to me and to the rest of the Haskell community. Thank you 👍

**Comment by dagit** [comment]
I second that. Thanks!
